[JENKINS-11354] CppCheck plugin cannot find CppCheck report [JENKINS-22823] Cppcheck plugin can't connect to report file
- Constructor IOException(Throwable cause) was introduced in Java 1.6 and is not compatible with Java 1.5.

FATAL: java.io.IOException: method <init>(Ljava/lang/Throwable;)V not found
java.lang.NoSuchMethodError: java.io.IOException: method <init>(Ljava/lang/Throwable;)V not found
at org.jenkinsci.plugins.cppcheck.parser.CppcheckParser.parse(CppcheckParser.java:56)